version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=mallorga
      - DB_PASSWORD=0781563
      - DB=products_management
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mallorga
      - POSTGRES_PASSWORD=0781563
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mallorga -d products_management"]
      interval: 10s
      timeout: 5s
      start_period: 5s
    volumes:
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
